### ISSUE TITLE
Installing Earthly plugin requires PHP plugin

### ISSUE THREAD

**Issue by bduisenov** [earthly/earthly-intellij-plugin#9]
This is quite unexpected that Earthly 0.0.3-ps rely on PHP. Is it really needed as a prerequisite?

<img width="594" alt="Screenshot 2022-12-13 at 11 31 15" src="https://user-images.githubusercontent.com/204085/207294129-32add663-b5f8-4128-a6eb-b3d2d7a47270.png">

**Comment by fooock** [comment]
I have the same problem and found something interesting. By default, seems the only available version in the IntelliJ repository is the `0.0.3-ps` (I suppose that `ps` is for PHP Storm). I'm using IntelliJ Ultimate.

<img width="629" alt="Captura de Pantalla 2023-03-31 a las 21 25 15" src="https://user-images.githubusercontent.com/19754597/229211283-a4e770ea-9e02-486a-bbee-87c51ba5d014.png">

In order to avoid installing PHP, you need to go to the official plugin page and download the raw version of the plugin. Here is the plugin page: https://plugins.jetbrains.com/plugin/20392-earthly/versions

After installing version 0.0.3 manually, I can use the plugin without PHP.

<img width="593" alt="Captura de Pantalla 2023-03-31 a las 21 28 29" src="https://user-images.githubusercontent.com/19754597/229211806-5307617c-953c-48fe-a8f7-a3868fe71945.png">

I hope this helps you.

**Comment by elonzh** [comment]
Version `0.0.3` is not compatible with IDEA 2023.1 now.

**Comment by idelvall** [comment]
I think the reason is the order of the releases we are doing. Seems like the IDE is picking the most recent one that is compatible. I will release the one with the least dependencies last and see if that fixes the issue.

BTW version `0.0.4` (DEA 2023.1 compatible) is now live @elonzh

**Comment by idelvall** [comment]
From what I've seen this new release seems to be picked first and solve the issue.
Can you guys please confirm that is the case?

**Comment by fooock** [comment]
@idelvall For IntelliJ, it works as expected, but in Goland, if I try to install the plugin then it picks `0.0.4-py` as the default

<img width="711" alt="Captura de Pantalla 2023-04-05 a las 23 57 01" src="https://user-images.githubusercontent.com/19754597/230220869-3ef50c3f-ed49-492d-b230-2305a5f6f089.png">

**Comment by idelvall** [comment]
Thanks @fooock, 
I will rearrange the order to: ij->go->py and that should fix the issue

**Comment by idelvall** [comment]
Ok, in a couple of days we'll have available version `0.0.5` with the new ordering. 

Fingers crossed! :)

![image](https://user-images.githubusercontent.com/5653455/231598298-4f44aec4-925d-4f33-91c4-10bc6d080e5c.png)

**Comment by idelvall** [comment]
Looks like it's fixed. Can you please confirm @fooock ?

**Comment by Jictyvoo** [comment]
Tested right now on Goland, it looks ok, I was finally able to uninstall the python plugin

**Comment by fooock** [comment]
yes, it is fixed 🚀 thank you!
